name: Build GO

on:
  push:
    branches:
      - '**'
    release:
      types:
        - published

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Quay Login
          uses: docker/login-action@v3
          with:
            registry: quay.io
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: quay.io/pieterjanae/alm-workshop

        - name: Build and push Docker image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
